### ISSUE TITLE
Contact Us form not displaying reCaptcha

### ISSUE THREAD

**Issue by shreddieb** [mageplaza/magento-2-google-recaptcha#13]
Hi, I installed the google recaptcha module, configured the settings with my invisible and visible site keys and secret keys. When I select "Contact Us" from the frontend configuration, the reCaptcha does not appear on my Contact Us form. However, other items in that list such as "Login" do show up.

If I instead add the reCaptcha as a "Custom Form Position" and add the form details for the Contact Us form, it then DOES show up on the page. However, the form submission gives a general error that the request is invalid or malformed.

This appears to be specific to only the Contact Us form from what I can tell.
My M2 version is 2.2.4

**Comment by bien119** [comment]
Hi,
"The request is invalid or malformed" message is shown up when there is something wrong in invisible configuration setting key. I suppose that you are misunderstanding between invisible setting and visible setting.

Note that:

- You should fill the visible key (http://prntscr.com/m87pzj) with recapcha v2 checkbox applicaiton information(http://prntscr.com/m87pqj).

- Invisible key (http://prntscr.com/m87q9m) with recapcha v2 Invisible (http://prntscr.com/m87qe5)

**Comment by shreddieb** [comment]
Hi @bien119, 
Thanks for the reply. I do in fact have the separate site key and secret key from my google recaptch admin...one set for Invisible and a different set for visible. The visible was generated with the "Checkbox" selected, while the invisible was generated with the "Invisible" selected. I have confirmed these reCaptcha site types are not mixed up in the M2 admin. You'll see from the frontend configuration section that I have "Contact Us" selected as one of the forms, but it actually doesn't show up when I have the config settings. The only way I got the invisible reCaptcha to show up was by entering the form details into the "Custom Form Position" section.
Any thoughts on why the reCaptcha might now show when the "Contact Us" is selected? That may be part of the issue.

![keys](https://user-images.githubusercontent.com/7809650/51291787-38903900-19bd-11e9-9bfb-0d1a6b1e6aca.png)

![fe-config](https://user-images.githubusercontent.com/7809650/51291777-30d09480-19bd-11e9-8e24-b0eb0f599b9e.png)

**Comment by bien119** [comment]
hi @shreddieb
The "Contact Us" is selected, but the Recaptcha does not show up because our configuration is based on the Magento default value. Specifically, "Form Post Paths" default value of "Contact us" field is "contact/index/post" and "CSS Selectors" default value is "#contact-form".
If you add "contact/index/post" to "Form Post Paths", There is the duplicate data issue will occors.
So my suggession, remove contact/index/post from Form Post Paths.
You just need to keep the CSS selectors back because this value is different from default value.

One more thing, make sure that you installed the Google Recaptcha library correctly. You can find it with the link bellow.

- https://github.com/mageplaza/magento-2-google-recaptcha/tree/library

- Library folder path: lib/internal/Mageplaza (https://i.imgur.com/Kh8q150.png)

**Comment by shreddieb** [comment]
Case closed! Thank you. The incorrect contact form id was the trick. I had changed that for a minor reason. But changing it back to the default and removing the "Custom Form Posiiton" paths did the trick. ReCaptcha is properly displayed and the contact form submits without error. Thank you!
