### ISSUE TITLE
Missing Captcha during Login after trying to add a product to wishlist

### ISSUE THREAD

**Issue by blackgamer84** [mageplaza/magento-2-google-recaptcha#25]
We lately discovered a missing function during a login that could propably cause a security issue and also results in breaking the "add to wishlist" function. 

Steps to repeat

- Visit product detail page without being logged in in magento 2.3.0 
- try to add the product to the wishlist 
- you are asked to log in, but the captcha module is missing
- you then can log in without solving the captcha first and get forwarded to the pdp again.

expected behaviour

Visit product detail page without being logged in in magento 2.3.0 
- try to add the product to the wishlist 
- you are asked to log in AND to see and solve the captcha module. 

This behaviour furthermore results in a magento error "request is invalid or malformed." and the "add to wishlist" process is unable to proceed and fails. 
In the end, users not logged in are therefore unable to add a product to the wishlist because their product gets lost due to the missing captcha and the following magento error.

**Comment by bien119** [comment]
Thank you for your information. Our team will check this issue and back to you as soon as possible.

**Comment by MpEdward** [comment]
I found out the problem. The main cause of this issue is because the captcha is validated twice.
You can fix this issue by following these steps below:

- Go to /Mageplaza/GoogleRecaptcha/Observer/Captcha.php

- Then add this code below in execute function:
`        if ($this->_request->getFullActionName() === 'wishlist_index_add') {
            return;
        }`
Screenshot:http://prntscr.com/nvrhqy

**Comment by MpEdward** [comment]
It was over 7 days and I didn't receive any reply so I will close this ticket.
Thank you!
